title: Birds Of Europe
logo: /assets/img/logo.jpg
email: vytautas.kersulis1@gmail.com
description: Minimalistic is a theme powered by Jekyll.
favicon: true
color-scheme: dark

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vaibhavvikas
  - name: twitter
    icon: <i class="fa-brands fa-twitter"></i>
    link: https://twitter.com/Vyce45

navigation:
  - name: Title
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Country List
    link: ./Birds-in-Europe.html
